### ISSUE TITLE
[General] Add Linux distributable

### ISSUE THREAD

**Issue by persn** [LateStartStudio/Hero6#187]
We need to find out we can and should distribute Hero6 in the same way we have an installer for Windows.

**Comment by persn** [comment]
Linux is notorious for not having a universal solution, however there are some candidates that have popped up over the years.

[Flatpak](http://flatpak.org/)
[AppImage](http://appimage.org/)

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

Since you are already building Hero6 for Ubuntu 12.04.5 LTS on Travis CI, it should be relatively easy to bundle that up as an AppImage. Possibly using https://github.com/probonopd/linuxdeployqt. Let me know if you need help.

**Comment by persn** [comment]
@probonopd Thank you for reaching out to us, it is much appreciated. I probably won't have time to look into this issue for another couple of months, but when that time comes I may have questions to ask you.

**Comment by persn** [comment]
We've discovered that dotnet CLI has a simple system for building our game with all dependencies included, so we're dropping the dedicated distributable in favor of a zip file with everything included

**Comment by probonopd** [comment]
> dotnet CLI has a simple system for building our game with all dependencies included

How does this work?

Wouldn't this be great ingredients for an AppImage?

**Comment by probonopd** [comment]
>  almost no one will be downloading the game from that AppImage, the actual released product will be most likely be distributed from a dedicated client like Steam which has it's own protocols

Isn't that much, much more hassle? Setting up Steam means a lot of work, whereas downloading an AppImage is easy.

**Comment by persn** [comment]
> Isn't that much, much more hassle? Setting up Steam means a lot of work, whereas downloading an AppImage is easy.

That's really not the point, we're going to support Steam anyways regardless of its setup because of it's market dominance, an extremely low minority will be getting it from other means.

> Why would one want to promote complex setups like Steam that create additional hassle?

I'm really not interested in making this into a bashing Steam discussion. The majority of people playing games use Steam, therefore we're going to support it, end of story. I'm getting the vibe that this discussion is headed in a extremely unproductive direction so I will lock it.
