### ISSUE TITLE
[General] Build Configuration Reversion

### ISSUE THREAD

**Issue by robertkety** [LateStartStudio/Hero6#191]
References to build configuration 'All' are being reverted to 'DefaultBuild' in:
src\Hero6.Installer.Windows\Hero6.Installer.Windows.aiproj
src\Hero6.Windows.sln

The specific cause for this is unknown, but the issue is reproducible on my machine running with the following:
Visual Studio Enterprise 2015 - Update 3
Advanced Installer 13.8.1

The reversion appear to occur when running build related tasks (i.e., build, rebuild, clean).

**Comment by robertkety** [comment]
I suspect this a compatibility issue with VS2015 trying to parse a sln file that was created in VS2017

**Comment by persn** [comment]
I am now actually experiencing the same issue on VS2017, it just started happening overnight, I'm wondering if that the problem lies within Advanced Installer rather than VS. Advanced Installer has some issues relating to source control in general, as we've already experienced as I had to request an update on the build server twice because of some screwups I did.

I've been thinking this before, and this is a good place to bring it up, maybe we just remove the project from the solution? The project extensions only works for Visual Studio, it isn't very good in the first place, I would never use it over the actual Advancer Installer UI which is just a few mouse clicks away. The only person that can modify the installer are the ones holding a license, so it'll only serve to annoy everyone else. The only place it benefits us is getting it built on our build servers, but aside from deployment I wonder if this is a really good idea? As it would mean that any random contributor would get a denied pull request because the installer failed, they most likely don't have a license so they can't do anything about it.

It's probably just better if we omitted it completely from the solution and updated it manually before version releases. We could also consider making a build step for it on [VSTS](https://marketplace.visualstudio.com/items?itemName=caphyon.AdvancedInstaller-BuildTask) that trigger on commit only, not on pull requests.

**Comment by persn** [comment]
I'm certain this is a bug in Advanced Installer VS extensions, these odd things started happening 2-3 days ago which is the same time a new version was uploaded. Also every time I start my IDE a new line is added to .aiproj `<PropertyGroup Condition=" '$(Configuration)' == 'DefaultBuild' " /> `, right now I have 6 occurrences of this line in a row.

**Comment by persn** [comment]
I believe this was resolved in #194
